/**
 * LOGOS Core — Partial draft confirmation boundary (Step 6.4).
 *
 * Provides:
 * - Incomplete draft header marker (createIncompleteDraftHeader)
 * - Minimal partial draft placeholder renderer (renderPartialDraftPlaceholder)
 * - Optional partial draft write plan executor (executePartialDraftWritePlan)
 *
 * These helpers enforce that incomplete documentation generation cannot happen
 * silently: outputs must be clearly marked incomplete, confirmation must be
 * explicit, and dry-run / declined confirmation must write nothing.
 *
 * Boundary: must not import Pi, Ink, React, TUI, or CLI modules.
 */

import type { LogosFilesystem } from '../ports/filesystem.js';
import type { GenerationPreflightIssue } from './preflight-result.js';
import { renderPartialDraftPlaceholder } from './render-output-placeholder.js';
import type { GenerationWritePlan } from './write-plan.js';

// ---------------------------------------------------------------------------
// Incomplete draft marker
// ---------------------------------------------------------------------------

export type IncompleteDraftMarkerInput = {
	title?: string;
	reason: string;
	checkedAt: string;
	blockers: GenerationPreflightIssue[];
	warnings: GenerationPreflightIssue[];
};

/**
 * Produce a Markdown front-matter + header that marks a file as an
 * incomplete LOGOS Engine partial draft.
 *
 * The returned text is deterministic for the same input, visible in
 * generated content, and must not claim final status.
 */
export function createIncompleteDraftHeader(
	input: IncompleteDraftMarkerInput,
): string {
	const blockerLines = input.blockers
		.map((b) => `#     - [${b.code}] ${b.message}`)
		.join('\n');

	const warningLines = input.warnings
		.map((w) => `#     - [${w.code}] ${w.message}`)
		.join('\n');

	const blockerSection =
		input.blockers.length > 0 ? `# Blockers:\n${blockerLines}\n#\n` : '';

	const warningSection =
		input.warnings.length > 0 ? `# Warnings:\n${warningLines}\n#\n` : '';

	return [
		'---',
		'logos:',
		'  generatedBy: logos-engine',
		'  generationMode: partial_draft',
		'  incomplete: true',
		'---',
		'',
		'# INCOMPLETE DRAFT',
		'',
		`Generated by LOGOS Engine as a partial draft on ${input.checkedAt}.`,
		'This file is not final documentation.',
		'Critical information may be missing, partial, or contradictory.',
		'',
		input.reason,
		'',
		'---',
		'',
		'## Preflight Status',
		'',
		blockerSection,
		warningSection,
	].join('\n');
}

// ---------------------------------------------------------------------------
// Partial draft write plan executor
// ---------------------------------------------------------------------------

export type ExecutePartialDraftWritePlanInput = {
	filesystem: LogosFilesystem;
	writePlan: GenerationWritePlan;
	preflight: {
		blockers: GenerationPreflightIssue[];
		warnings: GenerationPreflightIssue[];
		completenessScore: number;
		checkedAt: string;
	};
	now: string;
};

/**
 * Execute a partial draft write plan, writing only incomplete placeholder
 * content for operations with kind "create" or "update" that have no blockers.
 *
 * Rules:
 * - Never writes in dry-run mode.
 * - Never writes when writePlan.readyToWrite is false.
 * - Only writes operations with kind "create" or "update".
 * - Skipped operations with blockers are reported in skippedPaths.
 * - Uses renderPartialDraftPlaceholder for content.
 * - Does not render full documentation.
 * - Does not call AI.
 *
 * Returns the list of written and skipped paths.
 */
export async function executePartialDraftWritePlan(
	input: ExecutePartialDraftWritePlanInput,
): Promise<{
	writtenPaths: string[];
	skippedPaths: string[];
}> {
	const { filesystem, writePlan, preflight, now } = input;

	const writtenPaths: string[] = [];
	const skippedPaths: string[] = [];

	// Dry-run writes nothing.
	if (writePlan.dryRun) {
		for (const op of writePlan.operations) {
			if (op.kind === 'create' || op.kind === 'update') {
				skippedPaths.push(op.path);
			}
		}
		return { skippedPaths, writtenPaths };
	}

	// Not ready to write → skip everything.
	if (!writePlan.readyToWrite) {
		for (const op of writePlan.operations) {
			if (op.kind === 'create' || op.kind === 'update') {
				skippedPaths.push(op.path);
			}
		}
		return { skippedPaths, writtenPaths };
	}

	for (const op of writePlan.operations) {
		// Only create/update operations are writable.
		if (op.kind !== 'create' && op.kind !== 'update') {
			skippedPaths.push(op.path);
			continue;
		}

		// Skip operations that have blocker risks.
		const hasBlockers = op.risks.some(
			(r) =>
				r.code === 'unsafe_path' ||
				r.code === 'outside_project_root' ||
				r.code === 'path_traversal' ||
				r.code === 'write_plan_blocked_by_preflight',
		);
		if (hasBlockers) {
			skippedPaths.push(op.path);
			continue;
		}

		// Render placeholder content.
		const content = renderPartialDraftPlaceholder({
			now,
			operation: op,
			preflight: {
				blockers: preflight.blockers,
				checkedAt: preflight.checkedAt,
				completenessScore: preflight.completenessScore,
				warnings: preflight.warnings,
			},
		});

		try {
			await filesystem.writeTextFile({
				content,
				overwrite: op.kind === 'update',
				path: op.path,
				reason: 'partial_draft_placeholder',
			});
			writtenPaths.push(op.path);
		} catch {
			skippedPaths.push(op.path);
		}
	}

	return { skippedPaths, writtenPaths };
}
