/** Step 8.2 — Registers Module: first-class state-backed registers for decisions, assumptions, hypotheses, risks, and open questions */

export type { RegisterImpactContext } from './register-impact.js';
export {
	computeRegisterImpact,
	computeRegisterImpactSummary,
	getAffectedDocumentsForRegisterItem,
	getRegisterItemsAffectingDocument,
} from './register-impact.js';
export type { RegisterLifecycleOptions } from './register-lifecycle.js';
export {
	acceptRisk,
	activateHypothesis,
	confirmRegisterItem,
	createRegisterItem,
	getRegisterItem,
	invalidateHypothesis,
	linkRegisterItemToAffectedDocument,
	linkRegisterItemToSource,
	listRegisterItems,
	markHypothesisInconclusive,
	mitigateRisk,
	proposeRegisterItem,
	rejectRegisterItem,
	reopenOpenQuestion,
	resolveOpenQuestion,
	resolveRisk,
	reviseRegisterItem,
	supersedeRegisterItem,
	unlinkRegisterItemFromAffectedDocument,
	validateHypothesis,
} from './register-lifecycle.js';
export {
	getAssumptionRegister,
	getBlockingOpenQuestions,
	getDecisionRegister,
	getHypothesisRegister,
	getOpenQuestionRegister,
	getRegisterItemsByDocument,
	getRegisterItemsBySource,
	getRegisterItemsByStatus,
	getReviewRequiredRegisterItems,
	getRiskRegister,
	queryRegisters,
	summarizeRegisters,
	summarizeRegistersForDocument,
	summarizeRegistersForStatus,
} from './register-queries.js';
export {
	AnyRegisterItemSchema,
	AssumptionRegisterItemSchema,
	collectTokenFindings,
	DecisionRegisterItemSchema,
	HypothesisRegisterItemSchema,
	looksLikeTokenValue,
	OpenQuestionRegisterItemSchema,
	RegisterAffectedDocumentLinkSchema,
	RegisterConfidenceSchema,
	RegisterKindSchema,
	RegisterLifecycleEventSchema,
	RegisterLifecycleEventTypeSchema,
	RegisterOperationDiagnosticSchema,
	RegisterOperationInputSchema,
	RegisterReviewStateSchema,
	RegisterSourceLinkSchema,
	RiskRegisterItemSchema,
	redactTokenLikeValue,
	redactTokenValues,
} from './register-schema.js';
export type {
	AnyRegisterItem,
	AssumptionRegisterItem,
	AssumptionStatus,
	DecisionRegisterItem,
	DecisionStatus,
	HypothesisRegisterItem,
	HypothesisStatus,
	OpenQuestionRegisterItem,
	OpenQuestionStatus,
	RegisterAffectedDocumentLink,
	RegisterCollections,
	RegisterConfidence,
	RegisterCountsByConfidence,
	RegisterCountsByReviewState,
	RegisterCountsByStatus,
	RegisterGenerationImpact,
	RegisterImpactSummary,
	RegisterItem,
	RegisterItemId,
	RegisterKind,
	RegisterKindSummary,
	RegisterLifecycleEvent,
	RegisterLifecycleEventType,
	RegisterLifecycleTransition,
	RegisterOperationDiagnostic,
	RegisterOperationInput,
	RegisterOperationListResult,
	RegisterOperationResult,
	RegisterQuery,
	RegisterQueryResult,
	RegisterReviewState,
	RegisterSharedStatus,
	RegisterSourceLink,
	RegisterStatus,
	RegisterSummary,
	RegisterValidationSummary,
	RiskStatus,
} from './register-types.js';
export {
	REGISTER_CONFIDENCE_ORDER,
	REGISTER_CONFIDENCES,
	REGISTER_KIND_ORDER,
	REGISTER_KINDS,
	REGISTER_LIFECYCLE_EVENT_TYPE_ORDER,
	REGISTER_REVIEW_STATE_ORDER,
	REGISTER_REVIEW_STATES,
	REGISTER_STATUS_ORDER,
} from './register-types.js';
