/** Step 8.1 — Provenance module barrel exports */

// Builders
export {
	buildClaimSourceLinks,
	buildExecutiveItemProvenanceClaim,
	buildGeneratedSectionClaim,
	claimFromAssumption,
	claimFromDecision,
	claimFromExecutiveItemDraft,
	claimFromGeneratedSection,
	claimFromOpenQuestion,
	claimFromRisk,
	claimFromValidationFinding,
	resetProvenanceIdCounter,
	sourceFromAssumption,
	sourceFromConfirmedDecision,
	sourceFromConversationAnswer,
	sourceFromDocumentDescriptor,
	sourceFromExternalReference,
	sourceFromManualNote,
	sourceFromProfileDescriptor,
	sourceFromRepositoryScan,
	sourceFromValidationFinding,
} from './provenance-builders.js';
export type { ProvenanceQueryContext } from './provenance-queries.js';
// Queries
export {
	buildProvenanceGraph,
	resolveClaimsForDocument,
	resolveClaimsForSource,
	resolveProvenanceForArtifact,
	resolveSourceById,
	resolveSourcesForClaim,
	resolveSourcesForDocument,
	resolveSourcesForGeneratedSection,
	summarizeProvenance,
} from './provenance-queries.js';
// Schemas
export {
	ClaimConfidenceSchema,
	ClaimQuerySchema,
	ClaimRecordSchema,
	ClaimReviewStateSchema,
	ClaimStatusSchema,
	ClaimTypeSchema,
	SourceConfidenceSchema,
	SourceRecordSchema,
	SourceReferenceSchema,
	SourceStatusSchema,
	SourceTypeSchema,
	validateClaimRecord,
	validateClaimSourceLink,
	validateSourceRecord,
} from './provenance-schema.js';
// Types
export type {
	AssumptionSourceReference,
	ClaimConfidence,
	ClaimEvidence,
	ClaimId,
	ClaimLocation,
	ClaimQuery,
	ClaimQueryResult,
	ClaimRecord,
	ClaimResolutionDiagnostic,
	ClaimResolutionResult,
	ClaimReviewState,
	ClaimSourceLink,
	ClaimSourceLinkType,
	ClaimStatus,
	ClaimType,
	ConversationAnswerSourceReference,
	DecisionSourceReference,
	DocumentSectionClaim,
	DocumentSourceReference,
	ExecutiveItemClaim,
	ExternalReference,
	GeneratedContentClaim,
	ManualNoteSourceReference,
	ProfileDescriptorReference,
	ProvenanceBuilderContext,
	ProvenanceGraph,
	ProvenanceSummary,
	RepositoryScanReference,
	SourceConfidence,
	SourceId,
	SourceLocation,
	SourceMetadata,
	SourceRecord,
	SourceReference,
	SourceResolutionDiagnostic,
	SourceResolutionResult,
	SourceResolutionStatus,
	SourceStatus,
	SourceTimestamp,
	SourceType,
	ValidationFindingSourceReference,
} from './provenance-types.js';
export {
	CLAIM_CONFIDENCE_ORDER,
	CLAIM_CONFIDENCES,
	CLAIM_REVIEW_STATES,
	CLAIM_SOURCE_LINK_TYPES,
	CLAIM_STATUS_ORDER,
	CLAIM_STATUSES,
	CLAIM_TYPE_ORDER,
	CLAIM_TYPES,
	LINK_TYPE_ORDER,
	SOURCE_CONFIDENCES,
	SOURCE_STATUSES,
	SOURCE_TYPE_ORDER,
	SOURCE_TYPES,
} from './provenance-types.js';
