/** Step 11.3 — Executive HTML Export Adapter */

import { createHash } from 'node:crypto';
import type {
	ExecutiveExportAdapter,
	ExecutiveExportDiagnostic,
	ExecutiveExportInput,
	ExecutiveExportOptions,
	ExecutiveExportResult,
	ExecutiveExportResultMetadata,
	ExecutiveExportSecurityCheck,
	ExecutiveExportSecuritySummary,
} from './executive-export-model.js';
import type { ExecutivePlanJson } from './executive-plan-model.js';

// ---------------------------------------------------------------------------
// Adapter
// ---------------------------------------------------------------------------

export const executiveHtmlExportAdapter: ExecutiveExportAdapter = {
	kind: 'html',
	render,
	supportStatus: 'supported_file_export',
};

// ---------------------------------------------------------------------------
// HTML escaping
// ---------------------------------------------------------------------------

function escapeHtml(s: string): string {
	return s
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#39;');
}

function _escapeAttr(s: string): string {
	return s
		.replace(/&/g, '&amp;')
		.replace(/"/g, '&quot;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;');
}

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

const CSS = `
body { font-family: system-ui, -apple-system, sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem 1rem; color: #1a1a1a; line-height: 1.6; background: #fff; }
.warning-banner { background: #fff3cd; border: 2px solid #ffc107; padding: 1rem; margin: 1rem 0; border-radius: 4px; }
.warning-banner strong { color: #856404; }
.metadata-block { background: #f8f9fa; padding: 1rem; font-size: 0.85rem; border-radius: 4px; margin: 1rem 0; }
h1 { border-bottom: 2px solid #e0e0e0; padding-bottom: 0.5rem; }
h2 { border-bottom: 1px solid #e0e0e0; padding-bottom: 0.25rem; margin-top: 2rem; }
h3 { margin-top: 1.5rem; }
.status-badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 3px; font-size: 0.85rem; font-weight: 600; }
.status-blocked { background: #f8d7da; color: #721c24; }
.status-review { background: #fff3cd; color: #856404; }
.status-deferred { background: #e2e3e5; color: #383d41; }
.status-done { background: #d4edda; color: #155724; }
.status-planned { background: #cce5ff; color: #004085; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
th, td { border: 1px solid #dee2e6; padding: 0.5rem; text-align: left; }
th { background: #f8f9fa; }
code { background: #f4f4f4; padding: 0.15rem 0.3rem; border-radius: 2px; font-size: 0.9em; }
ul { padding-left: 1.5rem; }
pre { background: #f8f9fa; padding: 1rem; border-radius: 4px; overflow-x: auto; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e0e0e0; font-size: 0.85rem; color: #666; }
`.trim();

// ---------------------------------------------------------------------------
// HTML document structure
// ---------------------------------------------------------------------------

function htmlStart(title: string): string {
	const escapedTitle = escapeHtml(title);
	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapedTitle}</title>
<style>
${CSS}
</style>
</head>
<body>
`;
}

function htmlEnd(): string {
	return `
<footer>
  <p>Generated by LOGOS Engine — Executive Axis HTML Export</p>
  <p>This is a derived, non-canonical snapshot. No external systems were contacted.</p>
</footer>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Status badge
// ---------------------------------------------------------------------------

function statusBadge(status: string): string {
	let cls = 'status-planned';
	let label = status;
	switch (status) {
		case 'blocked':
			cls = 'status-blocked';
			label = '🚫 BLOCKED';
			break;
		case 'reviewing':
		case 'requires_review':
			cls = 'status-review';
			label = '👁️ REQUIRES REVIEW';
			break;
		case 'deferred':
		case 'draft':
			cls = 'status-deferred';
			label = status === 'deferred' ? '⏸️ DEFERRED' : 'Draft';
			break;
		case 'done':
			cls = 'status-done';
			label = '✅ Done';
			break;
		case 'ready':
		case 'planned':
			cls = 'status-planned';
			label = '📋 Planned';
			break;
	}
	return `<span class="status-badge ${cls}">${label}</span>`;
}

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

function renderWarningBanner(): string {
	return `<div class="warning-banner">
  <strong>⚠️ DERIVED / NON-CANONICAL SNAPSHOT</strong><br>
  This document is a derived Executive Axis HTML export snapshot.
  It is <strong>not</strong> a canonical source of truth.
  The canonical source of truth is the normative documentation baseline and structured <code>.logos/</code> state.
  This export does <strong>not</strong> represent live task management or external system state.
</div>`;
}

function renderMetadataSection(meta: ExecutiveExportResultMetadata): string {
	let html = '<div class="metadata-block"><strong>Export Metadata</strong><ul>';
	html += `<li>Source Plan: <code>${escapeHtml(meta.sourcePlanId)}</code></li>`;
	html += `<li>Plan Fingerprint: ${escapeHtml(meta.sourcePlanFingerprint)}</li>`;
	html += `<li>Profile: ${escapeHtml(meta.profileId)}${meta.profileVersion ? ` v${escapeHtml(meta.profileVersion)}` : ''}</li>`;
	html += `<li>Generated At: ${escapeHtml(meta.generatedAt)}</li>`;
	html += `<li>Readiness: <code>${escapeHtml(meta.readinessStatus)}</code></li>`;
	html += `<li>Derived Snapshot: true</li>`;
	html += `<li>Non-Canonical: true</li>`;
	html += `<li>External API Execution: false</li>`;
	if (meta.sourceCanonicalDocumentIds.length > 0) {
		html += '<li>Source Documents: <ul>';
		for (const docId of meta.sourceCanonicalDocumentIds) {
			html += `<li><code>${escapeHtml(docId)}</code></li>`;
		}
		html += '</ul></li>';
	}
	html += '</ul></div>';
	return html;
}

function renderSummarySection(plan: ExecutivePlanJson): string {
	let html = '<section><h2>Summary</h2>';
	html += '<table>';
	html += `<tr><th>Project</th><td>${escapeHtml(plan.project.name)} (${escapeHtml(plan.project.id)})</td></tr>`;
	html += `<tr><th>Plan ID</th><td><code>${escapeHtml(plan.id)}</code></td></tr>`;
	html += `<tr><th>Version</th><td>${escapeHtml(plan.version)}</td></tr>`;
	html += `<tr><th>Generated At</th><td>${escapeHtml(plan.generatedAt)}</td></tr>`;
	html += `<tr><th>Readiness</th><td><code>${escapeHtml(plan.source.readinessStatus)}</code></td></tr>`;
	html += `<tr><th>Confidence</th><td>${escapeHtml(plan.confidence.overall)}</td></tr>`;
	if (plan.project.description) {
		html += `<tr><th>Description</th><td>${escapeHtml(plan.project.description)}</td></tr>`;
	}
	html += '</table></section>';
	return html;
}

function renderReadinessSection(plan: ExecutivePlanJson): string {
	let html = '<section><h2>Readiness Snapshot</h2>';
	html += `<p>Status: <code>${escapeHtml(plan.source.readinessStatus)}</code></p>`;
	if (plan.source.warnings.length > 0) {
		html += '<p><strong>Warnings:</strong></p><ul>';
		for (const w of plan.source.warnings) {
			html += `<li>⚠️ ${escapeHtml(w)}</li>`;
		}
		html += '</ul>';
	}
	if (plan.metadata && typeof plan.metadata === 'object') {
		const meta = plan.metadata as Record<string, unknown>;
		if (meta.readinessSummary) {
			const rs = meta.readinessSummary as Record<string, unknown>;
			html += '<table><tr><th>Metric</th><th>Value</th></tr>';
			const metrics: Array<[string, unknown]> = [
				['Total Documents', rs.totalDocuments],
				['Satisfied', rs.satisfiedDocuments],
				['Warning', rs.warningDocuments],
				['Blocked', rs.blockedDocuments],
				['Blockers', rs.blockerCount],
			];
			for (const [k, v] of metrics) {
				html += `<tr><td>${escapeHtml(k)}</td><td>${v ?? 'N/A'}</td></tr>`;
			}
			html += '</table>';
		}
	}
	html += '</section>';
	return html;
}

function renderRoadmapsSection(plan: ExecutivePlanJson): string {
	if (!plan.execution.roadmaps || plan.execution.roadmaps.length === 0) {
		return '<section><h2>Roadmap</h2><p>No roadmaps defined.</p></section>';
	}
	let html = '<section><h2>Roadmap</h2>';
	for (const r of plan.execution.roadmaps) {
		html += `<h3>${escapeHtml(r.title)}</h3>`;
		html += `<p>${escapeHtml(r.description)}</p>`;
		html += '<table>';
		html += `<tr><th>Status</th><td>${statusBadge(r.status)}</td></tr>`;
		html += `<tr><th>Horizon</th><td>${escapeHtml(r.horizon)}</td></tr>`;
		html += `<tr><th>Milestones</th><td>${r.milestoneIds.map((m) => `<code>${escapeHtml(m)}</code>`).join(', ')}</td></tr>`;
		html += '</table>';
	}
	html += '</section>';
	return html;
}

function renderMilestonesSection(plan: ExecutivePlanJson): string {
	if (!plan.execution.milestones || plan.execution.milestones.length === 0) {
		return '<section><h2>Milestones</h2><p>No milestones defined.</p></section>';
	}
	let html = '<section><h2>Milestones</h2>';
	for (const m of plan.execution.milestones) {
		html += `<h3>${escapeHtml(m.title)}</h3>`;
		html += `<p>${statusBadge(m.status)} <code>${escapeHtml(m.id)}</code></p>`;
		html += `<p>${escapeHtml(m.objective)}</p>`;
		if (m.exitCriteria.length > 0) {
			html += '<p><strong>Exit Criteria:</strong></p><ul>';
			for (const c of m.exitCriteria) {
				html += `<li>${escapeHtml(c)}</li>`;
			}
			html += '</ul>';
		}
	}
	html += '</section>';
	return html;
}

function renderInitiativesSection(plan: ExecutivePlanJson): string {
	if (!plan.execution.initiatives || plan.execution.initiatives.length === 0) {
		return '<section><h2>Initiatives</h2><p>No initiatives defined.</p></section>';
	}
	let html = '<section><h2>Initiatives</h2>';
	for (const ini of plan.execution.initiatives) {
		html += `<h3>${escapeHtml(ini.title)}</h3>`;
		html += `<p>${statusBadge(ini.status)} <code>${escapeHtml(ini.id)}</code></p>`;
		html += `<p>${escapeHtml(ini.purpose)}</p>`;
		if (ini.deliverables.length > 0) {
			html += '<p><strong>Deliverables:</strong></p><ul>';
			for (const d of ini.deliverables) {
				html += `<li><code>${escapeHtml(d)}</code></li>`;
			}
			html += '</ul>';
		}
	}
	html += '</section>';
	return html;
}

function renderWorkItemsSection(plan: ExecutivePlanJson): string {
	if (!plan.execution.items || plan.execution.items.length === 0) {
		return '<section><h2>Work Items</h2><p>No work items defined.</p></section>';
	}
	let html = '<section><h2>Work Items</h2>';
	for (const item of plan.execution.items) {
		html += `<h3>${escapeHtml(item.title)}</h3>`;
		html += `<p>${statusBadge(item.status)} <code>${escapeHtml(item.id)}</code> | Type: <code>${escapeHtml(item.type)}</code> | Priority: <code>${escapeHtml(item.priority)}</code></p>`;
		html += `<p>${escapeHtml(item.description)}</p>`;
		if (item.acceptanceCriteria.length > 0) {
			html += '<p><strong>Acceptance Criteria:</strong></p><ul>';
			for (const c of item.acceptanceCriteria) {
				html += `<li>${escapeHtml(c)}</li>`;
			}
			html += '</ul>';
		}
		if (item.sourceNormativeDocuments.length > 0) {
			html += '<p><strong>Source Documents:</strong></p><ul>';
			for (const d of item.sourceNormativeDocuments) {
				html += `<li><code>${escapeHtml(d)}</code></li>`;
			}
			html += '</ul>';
		}
		if (item.dependsOn.length > 0) {
			html += '<p><strong>Dependencies:</strong></p><ul>';
			for (const d of item.dependsOn) {
				html += `<li><code>${escapeHtml(d)}</code></li>`;
			}
			html += '</ul>';
		}
	}
	html += '</section>';
	return html;
}

function renderBlockersSection(plan: ExecutivePlanJson): string {
	const blockers =
		plan.execution.items?.filter((i) => i.status === 'blocked') ?? [];
	const rcItems =
		plan.execution.items?.filter((i) => i.status === 'reviewing') ?? [];

	if (blockers.length === 0 && rcItems.length === 0) {
		return '<section><h2>Blockers &amp; Requires Review</h2><p>No blocked or review-required items.</p></section>';
	}
	let html = '<section><h2>Blockers &amp; Requires Review</h2>';

	if (blockers.length > 0) {
		html += '<h3>🚫 Blocked</h3><ul>';
		for (const b of blockers) {
			html += `<li><strong>${escapeHtml(b.title)}</strong> (<code>${escapeHtml(b.id)}</code>) — ${escapeHtml(b.priority)}</li>`;
		}
		html += '</ul>';
	}
	if (rcItems.length > 0) {
		html += '<h3>👁️ Requires Review</h3><ul>';
		for (const b of rcItems) {
			html += `<li><strong>${escapeHtml(b.title)}</strong> (<code>${escapeHtml(b.id)}</code>)</li>`;
		}
		html += '</ul>';
	}
	html += '</section>';
	return html;
}

function renderRisksSection(plan: ExecutivePlanJson): string {
	if (!plan.execution.risks || plan.execution.risks.length === 0) {
		return '<section><h2>Risks</h2><p>No risks recorded.</p></section>';
	}
	let html = '<section><h2>Risks</h2>';
	for (const r of plan.execution.risks) {
		html += `<h3>${escapeHtml(r.title)}</h3>`;
		html += `<p><code>${escapeHtml(r.id)}</code> | Likelihood: ${escapeHtml(r.likelihood)} | Impact: ${escapeHtml(r.impact)}</p>`;
		html += `<p>${escapeHtml(r.description)}</p>`;
		html += `<p><strong>Mitigation:</strong> ${escapeHtml(r.mitigation || 'None provided')}</p>`;
	}
	html += '</section>';
	return html;
}

function renderDecisionsSection(plan: ExecutivePlanJson): string {
	if (!plan.execution.decisions || plan.execution.decisions.length === 0) {
		return '<section><h2>Decisions</h2><p>No decisions recorded.</p></section>';
	}
	let html = '<section><h2>Decisions</h2>';
	for (const d of plan.execution.decisions) {
		html += `<h3>${escapeHtml(d.title)}</h3>`;
		html += `<p>${statusBadge(d.status)} <code>${escapeHtml(d.id)}</code></p>`;
		html += `<p>${escapeHtml(d.context || '')}</p>`;
		html += `<p><strong>Decision:</strong> ${escapeHtml(d.decision)}</p>`;
		if (d.consequences.length > 0) {
			html += '<p><strong>Consequences:</strong></p><ul>';
			for (const c of d.consequences) {
				html += `<li>${escapeHtml(c)}</li>`;
			}
			html += '</ul>';
		}
	}
	html += '</section>';
	return html;
}

function renderAcceptanceCriteriaSection(plan: ExecutivePlanJson): string {
	const allCriteria: { criterion: string; itemId: string }[] = [];
	for (const item of plan.execution.items ?? []) {
		for (const ac of item.acceptanceCriteria) {
			allCriteria.push({ criterion: ac, itemId: item.id });
		}
	}
	if (allCriteria.length === 0) {
		return '<section><h2>Acceptance Criteria</h2><p>No acceptance criteria defined.</p></section>';
	}
	let html = '<section><h2>Acceptance Criteria</h2><ul>';
	for (const ac of allCriteria) {
		html += `<li>(<code>${escapeHtml(ac.itemId)}</code>) ${escapeHtml(ac.criterion)}</li>`;
	}
	html += '</ul></section>';
	return html;
}

function renderTraceabilitySection(
	meta: ExecutiveExportResultMetadata,
): string {
	let html = '<section><h2>Traceability</h2>';
	html += '<table>';
	html += `<tr><th>Source Plan</th><td><code>${escapeHtml(meta.sourcePlanId)}</code></td></tr>`;
	html += `<tr><th>Fingerprint</th><td>${escapeHtml(meta.sourcePlanFingerprint)}</td></tr>`;
	html += `<tr><th>Profile</th><td>${escapeHtml(meta.profileId)}${meta.profileVersion ? ` v${escapeHtml(meta.profileVersion)}` : ''}</td></tr>`;
	html += `<tr><th>Readiness</th><td>${escapeHtml(meta.readinessStatus)}</td></tr>`;
	html += '</table>';
	if (meta.sourceCanonicalDocumentIds.length > 0) {
		html += '<h3>Source Canonical Documents</h3><ul>';
		for (const docId of meta.sourceCanonicalDocumentIds) {
			html += `<li><code>${escapeHtml(docId)}</code></li>`;
		}
		html += '</ul>';
	}
	html += '</section>';
	return html;
}

function renderExportMetadataSection(plan: ExecutivePlanJson): string {
	const exportConfigs = plan.exports ?? {};
	let html = '<section><h2>Export Targets</h2><ul>';
	for (const [key, config] of Object.entries(exportConfigs)) {
		const cfg = config as Record<string, unknown>;
		html += `<li><strong>${escapeHtml(key)}:</strong> enabled=${String(cfg.enabled ?? false)}, status=${escapeHtml(String(cfg.supportStatus ?? 'unknown'))}</li>`;
	}
	html += '</ul></section>';
	return html;
}

// ---------------------------------------------------------------------------
// Security checks
// ---------------------------------------------------------------------------

function runSecurityChecks(content: string): ExecutiveExportSecuritySummary {
	const checks: ExecutiveExportSecurityCheck[] = [
		{
			checkId: 'no_scripts',
			name: 'No script tags',
			passed: !/<script/i.test(content),
		},
		{
			checkId: 'no_inline_handlers',
			name: 'No inline event handlers',
			passed: !/\son\w+\s*=/i.test(content),
		},
		{
			checkId: 'no_external_stylesheets',
			name: 'No external stylesheets',
			passed: !/<link\s+rel=["']stylesheet/i.test(content),
		},
		{
			checkId: 'no_remote_fonts',
			name: 'No remote fonts',
			passed: !(
				/@import\s+url\(['"]https?:\/\//i.test(content) ||
				/url\(['"]https?:\/\//i.test(content)
			),
		},
		{
			checkId: 'no_iframes',
			name: 'No iframe tags',
			passed: !/<iframe/i.test(content),
		},
		{
			checkId: 'no_forms',
			name: 'No form tags',
			passed: !/<form/i.test(content),
		},
		{
			checkId: 'no_javascript_protocol',
			name: 'No javascript: protocol',
			passed: !/javascript:/i.test(content) && !/vbscript:/i.test(content),
		},
		{
			checkId: 'no_raw_tokens',
			name: 'No raw provider tokens',
			passed: !/sk-[a-zA-Z0-9]{20,}/.test(content),
		},
		{
			checkId: 'no_auth_headers',
			name: 'No authorization headers',
			passed: !/bearer [a-zA-Z0-9_.-]{20,}/i.test(content),
		},
		{
			checkId: 'no_canonical_claim',
			name: 'No canonical authority claim',
			passed: !content.includes('canonical source of truth: this document'),
		},
	];

	const allPassed = checks.every((c) => c.passed);
	return { checks, passed: allPassed };
}

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

function render(
	input: ExecutiveExportInput,
	options: ExecutiveExportOptions = {},
): ExecutiveExportResult {
	const diagnostics: ExecutiveExportDiagnostic[] = [];
	const plan = input.plan;
	const mapping = input.mapping;
	const timestamp = options.injectTimestamp ?? input.clock();
	const targetId = options.injectTargetId ?? `${mapping.mappingId}-html-export`;

	const sourceCanonicalDocIds: string[] = Array.isArray(
		plan.source.normativeDocuments,
	)
		? (plan.source.normativeDocuments as string[])
		: [];

	const meta: ExecutiveExportResultMetadata = {
		derivedSnapshot: true,
		externalApiExecution: false,
		generatedAt: timestamp,
		nonCanonical: true,
		profileId: input.profileId,
		profileVersion: input.profileVersion,
		readinessStatus: input.readinessStatus,
		schemaValidationStatus: 'passed',
		sourceCanonicalDocumentIds: sourceCanonicalDocIds,
		sourceCanonicalPaths: sourceCanonicalDocIds.map(
			(d) => `${input.documentationRoot}${d}.md`,
		),
		sourcePlanFingerprint: input.planFingerprint,
		sourcePlanId: input.planId,
	};

	const body = [
		renderWarningBanner(),
		renderMetadataSection(meta),
		renderSummarySection(plan),
		renderReadinessSection(plan),
		renderRoadmapsSection(plan),
		renderMilestonesSection(plan),
		renderInitiativesSection(plan),
		renderWorkItemsSection(plan),
		renderBlockersSection(plan),
		renderRisksSection(plan),
		renderDecisionsSection(plan),
		renderAcceptanceCriteriaSection(plan),
		renderTraceabilitySection(meta),
		renderExportMetadataSection(plan),
	].join('\n');

	const content = `${htmlStart(plan.project.name)}\n${body}\n${htmlEnd()}`;
	const checksum = createHash('sha256')
		.update(content)
		.digest('hex')
		.slice(0, 16);

	const outputPath =
		mapping.outputPath ??
		'outcomes/executive/exports/html/executive-overview.html';
	const securitySummary = runSecurityChecks(content);

	return {
		adapterKind: 'html',
		changedPaths: [],
		diagnostics,
		metadata: meta,
		readOnly: true,
		renderedFiles: [
			{
				checksum,
				content,
				format: 'html',
				relativePath: outputPath,
				targetId,
			},
		],
		securitySummary,
		supportStatus: 'supported_file_export',
		targetId,
		title: `Executive HTML Export: ${plan.project.name}`,
	};
}
