#!/usr/bin/env bash
# LOGOS Engine Launch Demo Script
# Simulates a complete App Business workflow for demo purposes.
# Requires: logos-engine built and available on PATH.

set -euo pipefail

DEMO_DIR="$(mktemp -d)"
trap 'rm -rf "$DEMO_DIR"' EXIT

echo "================================================"
echo " LOGOS Engine — App Business Workflow Demo"
echo "================================================"
echo ""
echo "This script demonstrates an end-to-end workflow"
echo "using the example workspace fixture."
echo ""
echo "Press Enter to advance through each step..."
echo ""

pause() {
  read -r
}

echo "--- Step 1: Project Initialization ---"
echo ""
echo "Creating a new LOGOS workspace in: $DEMO_DIR"
echo ""

mkdir -p "$DEMO_DIR"
cp -r tests/fixtures/example-workspace/.logos "$DEMO_DIR/.logos" 2>/dev/null || true
cp -r tests/fixtures/example-workspace/docs "$DEMO_DIR/docs" 2>/dev/null || true

echo "Workspace structure created:"
echo "  .logos/"
echo "    project.json       — Project metadata"
echo "    profile.lock.json  — Locked app-business profile"
echo "    answers.json       — Stored intake answers"
echo "    decisions.json     — Confirmed decisions"
echo "    config.json        — AI provider config"
echo ""
echo "(In a real session, you would run: logos + /init)"
pause

echo ""
echo "--- Step 2: AI-Led Conversational Intake ---"
echo ""
echo "The TUI opens a conversation. You describe your idea"
echo "in plain language. AI asks follow-up questions naturally."
echo ""
echo "Example conversation:"
echo ""
echo "  You: I'm building a scheduling app for personal trainers"
echo "       to manage their clients and sessions."
echo ""
echo "  AI:  That's a great start! What specific problem does this"
echo "       solve for personal trainers? How do they currently"
echo "       handle this without your app?"
echo ""
echo "  You: Trainers currently mix Google Calendar, WhatsApp, and"
echo "       spreadsheets. It's messy and wastes hours on admin."
echo ""
echo "AI interprets your answers into structured records, identifies"
echo "assumptions and open questions, and proposes decisions."
echo ""
echo "(In a real session, you just type in the TUI — no question IDs needed.)"
pause

echo ""
echo "--- Step 3: AI Decision Proposals ---"
echo ""
echo "Based on your answers, AI proposes structured decisions."
echo ""
echo "Example decisions:"
echo "  - Target market: Health & fitness professionals"
echo "  - Business model: B2B SaaS subscription"
echo "  - Pricing: Tiered monthly ($29/$79/$199)"
echo "  - Platform: iOS + Android (cross-platform)"
echo "  - Tech stack: React Native + Node.js + PostgreSQL"
echo ""
echo "AI proposals enter as 'proposed'. You confirm or reject each one."
echo ""
echo "(In a real session, you would review proposals in the TUI)"
pause

echo ""
echo "--- Step 4: Document Generation ---"
echo ""
echo "/generate creates the canonical App Business document tree:"
echo ""
echo "  docs/"
echo "    00-intake/"
echo "      IDEA_BRIEF.md"
echo "      ASSUMPTIONS.md"
echo "      OPEN_QUESTIONS.md"
echo "    01-market/"
echo "      MARKET_ANALYSIS.md"
echo "      COMPETITOR_MATRIX.md"
echo "      ICP.md"
echo "    02-business/"
echo "      BUSINESS_MODEL.md"
echo "      POSITIONING.md"
echo "    03-economics/"
echo "      PRICING.md"
echo "      FINANCIAL_MODEL.md"
echo "      BREAK_EVEN.md"
echo "    04-product/"
echo "      PRODUCT_THESIS.md"
echo "      MVP_SCOPE.md"
echo "      ROADMAP.md"
echo "    05-design/"
echo "      UX_FLOWS.md"
echo "      DESIGN_DIRECTION.md"
echo "      ONBOARDING.md"
echo "    06-architecture/"
echo "      ARCHITECTURE.md"
echo "      TECH_STACK.md"
echo "      DATA_MODEL.md"
echo "      API_SPEC.md"
echo "    07-implementation/"
echo "      IMPLEMENTATION_PLAN.md"
echo "      DEVELOPMENT_STANDARDS.md"
echo "    08-testing/"
echo "      TESTING_STRATEGY.md"
echo "    09-go-to-market/"
echo "      MARKETING_STRATEGY.md"
echo "      LAUNCH_PLAN.md"
echo "      CONTENT_STRATEGY.md"
echo "    10-operations/"
echo "      OPERATIONS.md"
echo "      SUPPORT_MODEL.md"
echo "      METRICS.md"
echo "    11-governance/"
echo "      DECISION_LOG.md"
echo "      RISK_REGISTER.md"
echo ""
echo "(In a real session, you would run: /generate)"
pause

echo ""
echo "--- Step 5: Validation ---"
echo ""
echo "/validate checks for:"
echo "  - Required decisions (missing?)"
echo "  - Dependencies (broken?)"
echo "  - Phase readiness (which phases are complete?)"
echo "  - Consistency (contradictions?)"
echo "  - Risk patterns (high-risk combinations?)"
echo ""
echo "(In a real session, you would run: /validate)"
pause

echo ""
echo "--- Step 6: Diagnostics ---"
echo ""
echo "/diagnose provides:"
echo "  - Gap summary"
echo "  - Risk analysis"
echo "  - Next conversational move recommendations"
echo "  - Affected documents"
echo ""
echo "(In a real session, you would run: /diagnose)"
pause

echo ""
echo "--- Step 7: Iterate ---"
echo ""
echo "Update answers, review new proposals, regenerate documents."
echo ""
echo "The workspace is Git-friendly. Commit everything:"
echo ""
echo "  git add .logos/ docs/"
echo "  git commit -m 'Initialize app business documentation'"
echo ""
pause

echo ""
echo "================================================"
echo " Demo Complete"
echo "================================================"
echo ""
echo "To try it yourself:"
echo ""
echo "  pnpm install && pnpm build"
echo "  logos"
echo "  /init"
echo ""
echo "See README.md and docs/ for more."
