/** Logo Engine — package metadata and scaffold types */

export const PACKAGE_NAME = 'logos-engine';
export const PACKAGE_VERSION = '0.1.0';
export const LOGOS_BINARY_NAME = 'logos';

export type LogosRuntimeMode = 'cli' | 'tui' | 'api';

export interface LogosPackageMetadata {
	name: string;
	version: string;
	binaryName: string;
}

export function getPackageMetadata(): LogosPackageMetadata {
	return {
		binaryName: LOGOS_BINARY_NAME,
		name: PACKAGE_NAME,
		version: PACKAGE_VERSION,
	};
}

// Step 4.2 — AI Provider Port
export type {
	AiProviderCapabilities,
	AiProviderConsent,
	AiProviderDiagnostic,
	AiProviderDisclosure,
	AiProviderExecutionMode,
	AiProviderId,
	AiProviderKind,
	AiProviderOperation,
	AiProviderPort,
	AiProviderRequest,
	AiProviderResponse,
	AiProviderResponseValidationResult,
	ConversationMessage,
	ConversationOperationRequest,
	ConversationOperationResponse,
	DisclosureContextCategory,
	DisclosureGuardOptions,
	DisclosureGuardResult,
	FakeProviderOptions,
	ProviderConsentRecord,
	StartupBriefingItem,
	StartupBriefingRequest,
	StartupBriefingResponse,
	StructuredExtractionRecord,
	StructuredExtractionRequest,
	StructuredExtractionResponse,
	SuggestionItem,
	SuggestionRequest,
	SuggestionResponse,
} from './ai/index.js';
export {
	assertAllRecordsProposed,
	assertDisclosureConsent,
	checkProviderDisclosure,
	DISCLOSURE_CONTEXT_CATEGORIES,
	FakeProvider,
	validateConversationResponse,
	validateProviderResponse,
	validateStartupBriefingResponse,
	validateStructuredExtractionResponse,
	validateSuggestionResponse,
} from './ai/index.js';
// Step 3.2 — Safe Filesystem Writes
export type {
	AtomicJsonWriteOptions,
	BackupOptions,
	BackupResult,
	DryRunWritePlan,
	PathSafetyOptions,
	SafeFsAdapter,
	SafeWriteChangedPath,
	SafeWriteChangedPathRole,
	SafeWriteDiagnostic,
	SafeWriteOptions,
	SafeWritePolicy,
	SafeWriteResult,
} from './fs/safe-filesystem.js';
export {
	checkPathSafety,
	createBackup,
	resolveWritePolicy,
	serializeJson,
	writeFileAtomic,
	writeJsonAtomic,
} from './fs/safe-filesystem.js';
// Step 3.3 — Init Workspace Creation
export type {
	InitWorkspaceChangedPath,
	InitWorkspaceCollision,
	InitWorkspaceCollisionKind,
	InitWorkspaceDiagnostic,
	InitWorkspaceDocumentationRootSelection,
	InitWorkspaceMode,
	InitWorkspaceOptions,
	InitWorkspacePlan,
	InitWorkspacePreflightResult,
	InitWorkspaceProfileSelection,
	InitWorkspaceResult,
	InitWorkspaceTargetPaths,
} from './init/index.js';
export {
	initWorkspace,
	planInitWorkspace,
	preflightInit,
} from './init/index.js';
// Step 4.1 — Question Planning from Profile Contracts
// Step 4.2 — Intake Context Builder, Redaction, and Provider Request Builders
// Step 4.3 — Proposal Mapping, Lifecycle, and Repository
// Step 4.4 — Startup Briefing and Contextual Suggestions
export type {
	AcceptProposalOptions,
	BuildAiStartupBriefingOptions,
	BuildConversationRequestOptions,
	BuildStructuredExtractionRequestOptions,
	BuildSuggestionRequestOptions,
	ContextualSuggestion,
	ContextualSuggestionDiagnostic,
	ContextualSuggestionInput,
	ContextualSuggestionKind,
	ContextualSuggestionReason,
	ContextualSuggestionRenderOptions,
	ContextualSuggestionResult,
	ContextualSuggestionSource,
	ContextualSuggestionStatus,
	CreateProposalOptions,
	CreateProposalResult,
	GetProposalOptions,
	GetProposalResult,
	IntakeContext,
	IntakeContextAssumption,
	IntakeContextBuilderInput,
	IntakeContextBuilderOptions,
	IntakeContextDecision,
	IntakeContextDiagnostic,
	IntakeContextDocumentReference,
	IntakeContextOpenQuestion,
	IntakeContextProfileReference,
	IntakeContextRedactionResult,
	IntakeContextRelevantAnswer,
	IntakeContextRisk,
	IntakeContextScope,
	IntakeContextSection,
	IntakeContextValidationGap,
	ListProposalsOptions,
	ListProposalsResult,
	PlannedQuestion,
	ProposalDiagnostic,
	ProposalDocumentContentHint,
	ProposalEvidence,
	ProposalExtractionMetadata,
	ProposalHypothesis,
	ProposalId,
	ProposalKind,
	ProposalLifecycleResult,
	ProposalMappingAnswer,
	ProposalMappingInput,
	ProposalMappingResult,
	ProposalReviewAction,
	ProposalRevision,
	ProposalRiskType,
	ProposalSource,
	ProposalStatus,
	QuestionBlockingLevel,
	QuestionCandidate,
	QuestionCluster,
	QuestionDuplicateKey,
	QuestionGap,
	QuestionPlanningDiagnostic,
	QuestionPlanningInput,
	QuestionPlanningOptions,
	QuestionPlanningResult,
	QuestionPlanReason,
	QuestionPlanStatus,
	QuestionPriority,
	QuestionSource,
	RejectProposalOptions,
	ReviewableProposal,
	ReviseProposalOptions,
	StartupBriefing,
	StartupBriefingAction,
	StartupBriefingDiagnostic,
	StartupBriefingFallbackReason,
	StartupBriefingInput,
	StartupBriefingMode,
	StartupBriefingRenderOptions,
	StartupBriefingResult,
	StartupBriefingSection,
	StartupBriefingSource,
	StartupBriefingStatus,
	UpdateProposalStatusOptions,
	UpdateProposalStatusResult,
} from './intake/index.js';
export {
	acceptProposal,
	buildAiStartupBriefing,
	buildConversationRequest,
	buildDeterministicStartupBriefing,
	buildIntakeContext,
	buildStartupBriefingRequest,
	buildStructuredExtractionRequest,
	buildSuggestionRequest,
	collectQuestionCandidates,
	createProposal,
	createProposals,
	DEFAULT_BRIEFING_RENDER_OPTIONS,
	DEFAULT_BUILDER_OPTIONS,
	DEFAULT_SUGGESTION_RENDER_OPTIONS,
	generateContextualSuggestions,
	getProposal,
	isSecretKey,
	isTokenLike,
	listProposals,
	listProposalsFromState,
	mapAnswersToProposals,
	planNextQuestions,
	redactIntakeContext,
	rejectProposal,
	renderContextualSuggestions,
	renderStartupBriefing,
	resetSuggestionCounter,
	reviseProposal,
	updateProposalStatus,
} from './intake/index.js';
export type {
	AgentPackOutputDeclaration,
	ArtifactOutputDeclaration,
	BuildContractGraphOptions,
	BuildContractGraphResult,
	CanonicalOutputDeclaration,
	ContractGraph,
	ContractGraphDiagnostic,
	ContractGraphEdge,
	ContractGraphNode,
	DataOutputDeclaration,
	DependencyReference,
	DependencyReferenceKind,
	DependencyTargetKind,
	ExecutiveOutputDeclaration,
	OutputDeclaration,
	OutputDeclarationKind,
	OutputDeclarationRole,
	StatusTransition,
	StatusTransitionResult,
	StatusValue,
	StatusWorkflow,
} from './profiles/contract-graph.js';
export {
	buildContractGraph,
	buildStatusWorkflow,
	ContractGraphError,
	canTransitionStatus,
} from './profiles/contract-graph.js';
export type {
	DocumentDescriptor,
	DocumentDescriptorDependency,
	DocumentDescriptorId,
	DocumentDescriptorOutput,
	DocumentDescriptorOutputAgentPack,
	DocumentDescriptorOutputArtifact,
	DocumentDescriptorOutputCanonical,
	DocumentDescriptorOutputData,
	DocumentDescriptorOutputExecutive,
	DocumentDescriptorSection,
	DocumentDescriptorStatus,
	DocumentDescriptorValidationError,
	DocumentDescriptorValidationOptions,
	DocumentDescriptorValidationResult,
	DocumentSchema,
	LoadAndValidateDocumentDescriptorOptions,
	SchemaFieldDef,
} from './profiles/document-descriptor.js';
export {
	DocumentDescriptorValidationErrorClass,
	loadAndValidateDocumentDescriptor,
	loadDocumentSchema,
	setDocumentSchemaForValidation,
	validateDocumentDescriptor,
} from './profiles/document-descriptor.js';
export type {
	CanonicalDocumentId,
	DocumentationContract,
	DocumentationContractDiagnostic,
	DocumentationContractIndexEntry,
	DocumentationContractPaths,
	DocumentDescriptorPath,
	LoadDocumentationContractOptions,
	LoadedDocumentDescriptor,
	LoadedPhaseDescriptor,
	PhaseDocumentRef,
	PhaseId,
} from './profiles/documentation-contract.js';
export {
	DocumentationContractError,
	listDocumentationContractIndex,
	loadDocumentationContract,
	relativizeIndexPaths,
} from './profiles/documentation-contract.js';
export type {
	LoadProfileRegistryOptions,
	ProfileAgentPolicy,
	ProfileAxis,
	ProfileDependencyPolicy,
	ProfileGlobalRules,
	ProfileId,
	ProfileOutputModel,
	ProfileOutputModelEntry,
	ProfilePhaseRegistry,
	ProfilePhaseRegistryEntry,
	ProfileQualityModel,
	ProfileRegistry,
	ProfileRegistryDiagnostic,
	ProfileRegistryPaths,
	ProfileRoadmapIntegration,
	ProfileStatusWorkflow,
} from './profiles/profile-registry.js';
export {
	loadProfileRegistry,
	ProfileRegistryError,
	validateProfileRegistry,
} from './profiles/profile-registry.js';
// Step 2.4 — Error, Logging, Dry-Run, and JSON Result Conventions
// Step 13.1 — Harden Error and Recovery Model
export type {
	CommandChangedPath,
	CommandError,
	CommandExecutionMode,
	CommandMessage,
	CommandResult,
	CommandResultMetadata,
	CommandStatus,
	CommandWarning,
	CreateCommandResultOptions,
	DiagnosticArea,
	JsonSerializableCommandResult,
	LoggerOptions,
	LogLevel,
	LogosChangedPath,
	LogosChangedPathAction,
	LogosDiagnostic,
	LogosDiagnosticCode,
	LogosDiagnosticInput,
	LogosDiagnosticRelatedIds,
	LogosDiagnosticSeverity,
	LogosNextAction,
	LogosNextActionCategory,
	LogosOperationStatus,
	LogosPartialFailure,
	LogosRecoveryHint,
	LogosRecoveryHintCategory,
	LogSink,
	MemoryLogSink,
	RedactionOptionsType,
	StructuredError,
	StructuredErrorOptions,
} from './runtime/index.js';
export {
	CHANGED_PATH_ACTION_ORDER,
	ConsoleLogSink,
	changedPathsFromLogos,
	compareSeverity,
	createCommandResult,
	createDiagnostic,
	createStructuredError,
	DIAGNOSTIC_AREAS,
	DIAGNOSTIC_SEVERITY_ORDER,
	defaultLogger,
	diagnosticCode,
	diagnosticToJson,
	diagnosticToStructuredError,
	ErrorCodes,
	formatCommandResultForHuman,
	formatDiagnosticForTerminal,
	formatDiagnosticsForTerminal,
	formatStructuredError,
	formatStructuredErrors,
	Logger,
	OPERATION_STATUS_ORDER,
	operationStatusToCommandStatus,
	RECOVERY_HINT_CATEGORIES,
	RecoveryHints,
	recoveryHint,
	redactAndRelativize,
	redactString,
	redactValue,
	relativizePaths,
	sortChangedPaths,
	sortDiagnostics,
	sortNextActions,
	statusToExitCode,
	structuredErrorToDiagnostic,
	toCommandError,
	toJsonSerializable,
	UNKNOWN_ERROR_CODE,
	wrapUnknownCaughtValue,
	wrapUnknownError,
} from './runtime/index.js';
export type {
	DetectProjectContextOptions,
	DocumentationRootConfig,
	ProjectContext,
	ProjectContextDiagnostic,
	ProjectContextError,
	ProjectRootDetectionResult,
	ProjectRootKind,
	ProviderConfigStatus,
	WorkspaceConfigDetectionResult,
	WorkspaceDetectionResult,
	WorkspaceInitializationState,
} from './runtime/project-context.js';
export {
	detectProjectContext,
	detectProjectRoot,
	detectWorkspace,
	detectWorkspaceConfig,
	formatInitializationState,
	formatProjectContextLines,
	formatProviderStatus,
} from './runtime/project-context.js';
// Step 3.4 — Artifact Registry
export type {
	ArtifactRegistryEntryInput,
	ArtifactSummary,
	ListArtifactsOptions,
	RegisterArtifactOptions,
	UpdateArtifactRecordOptions,
} from './state/artifact-registry.js';
export {
	isArtifactCanonical,
	listArtifacts,
	registerArtifact,
	summarizeArtifacts,
	updateArtifactRecord,
} from './state/artifact-registry.js';
// Step 3.4 — Run Repository
export type {
	CreateRunRecordOptions,
	ListRunRecordsOptions,
	RunRecordInput,
	RunSummary,
	UpdateRunRecordOptions,
} from './state/run-repository.js';
export {
	createRunRecord,
	listRunRecords,
	summarizeRuns,
	updateRunRecord,
} from './state/run-repository.js';
// Step 3.4 — Session Repository
export type {
	CreateSessionRecordOptions,
	ListSessionRecordsOptions,
	SessionRecordInput,
	SessionSummary,
	UpdateSessionRecordOptions,
} from './state/session-repository.js';
export {
	createSessionRecord,
	getCurrentSessionSummary,
	listSessionRecords,
	updateSessionRecord,
} from './state/session-repository.js';
// Step 3.1 — Workspace State Schemas
export type {
	WorkspaceArtifact,
	WorkspaceAssumption,
	WorkspaceAuditEvent,
	WorkspaceDecision,
	WorkspaceDocumentationRootConfig,
	WorkspaceGenerationRun,
	WorkspaceMigrationRecord,
	WorkspaceOpenQuestion,
	WorkspaceProfileLock,
	WorkspaceProposal,
	WorkspaceProviderConfigReference,
	WorkspaceRisk,
	WorkspaceSession,
	WorkspaceState,
	WorkspaceValidationRun,
} from './state/workspace-state.schema.js';
export {
	ArtifactStatusSchema,
	ArtifactTypeSchema,
	AssumptionStatusSchema,
	DecisionStatusSchema,
	DocumentationRootConfigSchema,
	GenerationRunStatusSchema,
	MigrationStatusSchema,
	OpenQuestionStatusSchema,
	ProfileSourceSchema,
	ProposalKindSchema,
	ProposalStatusSchema,
	RiskSeveritySchema,
	RiskStatusSchema,
	SessionStatusSchema,
	SessionTypeSchema,
	TokenSourceSchema,
	ValidationRunStatusSchema,
	WORKSPACE_STATE_SCHEMA_VERSION,
	WorkspaceArtifactSchema,
	WorkspaceAssumptionSchema,
	WorkspaceAuditEventSchema,
	WorkspaceDecisionSchema,
	WorkspaceGenerationRunSchema,
	WorkspaceMetadataSchema,
	WorkspaceMigrationRecordSchema,
	WorkspaceOpenQuestionSchema,
	WorkspaceProfileLockSchema,
	WorkspaceProposalSchema,
	WorkspaceProviderConfigReferenceSchema,
	WorkspaceRiskSchema,
	WorkspaceSessionSchema,
	WorkspaceStateSchema,
	WorkspaceValidationRunSchema,
} from './state/workspace-state.schema.js';
export type { CreateDefaultWorkspaceStateOptions } from './state/workspace-state-defaults.js';
export { createDefaultWorkspaceState } from './state/workspace-state-defaults.js';
// Step 3.4 — Workspace State Repository
export type {
	Clock,
	WorkspaceStateReadOptions,
	WorkspaceStateReadResult,
	WorkspaceStateRepositoryDiagnostic,
	WorkspaceStateUpdateOptions,
	WorkspaceStateUpdateResult,
	WorkspaceStateWriteOptions,
	WorkspaceStateWriteResult,
} from './state/workspace-state-repository.js';
export {
	readWorkspaceState,
	requireWorkspaceState,
	updateWorkspaceState,
	writeWorkspaceState,
} from './state/workspace-state-repository.js';
export type {
	WorkspaceStateValidationError,
	WorkspaceStateValidationResult,
} from './state/workspace-state-validation.js';
export {
	isLikelyRawSecret,
	parseWorkspaceState,
	redactSecretValue,
	safeParseWorkspaceState,
	validateWorkspaceState,
} from './state/workspace-state-validation.js';
// Step 3.4 — Workspace Status
export type {
	WorkspaceStatusQueryOptions,
	WorkspaceStatusSummary,
} from './state/workspace-status.js';
export { getWorkspaceStatusSummary } from './state/workspace-status.js';

// ---------------------------------------------------------------------------
// Step 5.1 — Generation Planner
// ---------------------------------------------------------------------------

export type {
	DependencySatisfaction,
	GenerationAction,
	GenerationBlocker,
	GenerationDependencyState,
	GenerationDryRunSummary,
	GenerationGap,
	GenerationOutputTarget,
	GenerationPlan,
	GenerationPlanDiagnostic,
	GenerationPlanInput,
	GenerationPlanItem,
	GenerationPlanOptions,
	GenerationPlanResult,
	GenerationPlanSummaryCounts,
	GenerationReadiness,
	GenerationStalenessReason,
} from './generation/index.js';
export {
	createGenerationPlan,
	planDocumentGeneration,
	summarizeGenerationPlan,
} from './generation/index.js';

// ---------------------------------------------------------------------------
// Step 5.2 — Canonical Markdown Renderer
// ---------------------------------------------------------------------------

export type {
	CanonicalMarkdownDocument,
	CanonicalMarkdownRenderDiagnostic,
	CanonicalMarkdownRenderInput,
	CanonicalMarkdownRenderOptions,
	CanonicalMarkdownRenderResult,
	ConfirmedStateCollections,
	MarkdownGapMarker,
	MarkdownLanguagePolicy,
	MarkdownMetadataHeader,
	MarkdownQualityNote,
	MarkdownSectionRenderStatus,
	MarkdownSourceReference,
	MarkdownTraceabilityReference,
	RenderedMarkdownSection,
	RenderFromPlanInput,
	SectionRenderContext,
} from './generation/index.js';
export {
	renderCanonicalMarkdownDocument,
	renderCanonicalMarkdownFromPlan,
} from './generation/index.js';

// ---------------------------------------------------------------------------
// Step 5.3 — Safe Markdown Writer
// ---------------------------------------------------------------------------

export type {
	GeneratedMarkdownMetadata,
	ManualEditDetectionInput,
	ManualEditDetectionResult,
	ManualEditFsAdapter,
	ManualEditStatus,
	MarkdownChecksum,
	MarkdownFileMetadata,
	MarkdownFileTraceabilityRef,
	MarkdownWriteChangedPath,
	MarkdownWriteChangedPathRole,
	MarkdownWriteCollision,
	MarkdownWriteDiagnostic,
	MarkdownWritePlan,
	MarkdownWritePlanItem,
	MarkdownWritePlanSummary,
	MarkdownWriteStatus,
	SafeMarkdownWriteInput,
	SafeMarkdownWriteOptions,
	SafeMarkdownWritePolicy,
	SafeMarkdownWriteResult,
} from './generation/index.js';
export {
	computeBodyChecksum,
	computeFullChecksum,
	detectManualEdit,
	injectChecksumIntoMarkdown,
	parseFrontmatter,
	planMarkdownWrites,
	resolveMarkdownWriteAction,
	writeMarkdownDocuments,
} from './generation/index.js';

// ---------------------------------------------------------------------------
// Step 5.4 — Generate Canonical Docs Orchestration
// ---------------------------------------------------------------------------

export type {
	GenerateCanonicalDocsDiagnostic,
	GenerateCanonicalDocsDryRunResult,
	GenerateCanonicalDocsMode,
	GenerateCanonicalDocsOptions,
	GenerateCanonicalDocsPreflight,
	GenerateCanonicalDocsReportItem,
	GenerateCanonicalDocsResult,
	GenerateCanonicalDocsWritePolicy,
} from './generation/index.js';
export {
	executeGenerateCanonicalDocs,
	generateCanonicalDocs,
	planGenerateCanonicalDocs,
} from './generation/index.js';

// ---------------------------------------------------------------------------
// Step 6.1 — Deterministic Validation Service
// ---------------------------------------------------------------------------

export type {
	ValidationDiagnostic,
	ValidationFinding,
	ValidationFindingCode,
	ValidationFindingLocation,
	ValidationFindingRecoveryHint,
	ValidationFindingSeverity,
	ValidationFindingSource,
	ValidationGateStatus,
	ValidationRunInput,
	ValidationRunOptions,
	ValidationRunResult,
	ValidationScope,
	ValidationSummary,
	ValidationTarget,
} from './validation/index.js';
export {
	createValidationFinding,
	createValidationRunResult,
	determineValidationGateStatus,
	looksLikeSecretLikeValue,
	redactSecretLikeString,
	redactValidationValue,
	sortValidationFindings,
	summarizeValidationFindings,
	VALIDATION_FINDING_SORT_ORDER,
	validateArtifactRegistry,
	validateContracts,
	validateGeneratedOutputMetadata,
	validateWorkspace,
	validateWorkspaceState as validateWorkspaceStateScope,
	validationSchemas,
} from './validation/index.js';

// ---------------------------------------------------------------------------
// Step 6.2 — Document Completeness and Semantic Lints
// ---------------------------------------------------------------------------

export type {
	DocumentSemanticLintContext,
	DocumentSemanticLintInput,
	DocumentSemanticLintOptions,
	DocumentSemanticLintResult,
	DocumentSemanticLintRule,
	DocumentSemanticLintRuleId,
	DocumentSemanticLintRuleResult,
	MarkdownDocumentStructure,
	MarkdownHeadingIndex,
	MarkdownLintDiagnostic,
} from './validation/index.js';
export {
	createSemanticLintRules,
	lintCanonicalMarkdownDocument,
	lintCanonicalMarkdownDocuments,
	parseMarkdownStructure,
	SEMANTIC_LINT_RULE_REGISTRY,
} from './validation/index.js';

// ---------------------------------------------------------------------------
// Step 6.3 — /validate, /diagnose, and Review Reports
// ---------------------------------------------------------------------------

export type {
	DiagnoseCommandData,
	DiagnoseCommandMode,
	DiagnoseCommandOptions,
	DiagnosticExplanation,
	DiagnosticFindingGroup,
	DiagnosticInterpretation,
	DiagnosticInterpretationSource,
	DiagnosticSuggestedAction,
	ValidateCommandData,
	ValidateCommandMode,
	ValidateCommandOptions,
	ValidateCommandScope,
	ValidationReportArtifact,
	ValidationReportFormat,
	ValidationReportKind,
	ValidationReportParams,
	ValidationReportSummary,
	ValidationReportWritePolicy,
} from './validation/index.js';

export {
	computeReportChecksum,
	createReportSummary,
	planReportPath,
	renderValidationReportJson,
	renderValidationReportMarkdown,
	runDiagnoseCommand,
	runValidateCommand,
} from './validation/index.js';

// ---------------------------------------------------------------------------
// Step 7.1 — Dependency Graph
// ---------------------------------------------------------------------------

export type {
	DependencyGraphBuildInput,
	DependencyGraphBuildOptions,
	DependencyGraphBuildResult,
	DependencyGraphCycle,
	DependencyGraphDiagnostic,
	DependencyGraphEdge,
	DependencyGraphEdgeId,
	DependencyGraphEdgeKind,
	DependencyGraphNode,
	DependencyGraphNodeId,
	DependencyGraphNodeKind,
	DependencyGraphSummary,
	DependencyGraphTraversalOptions,
	DependencyGraphTraversalResult,
	DependencyGraphUnresolvedReference,
	DocumentDependencyGraph,
	ExecutiveCfgExportTarget,
	ExecutiveCfgOutput,
	ExecutiveGenerationConfig,
	GraphJsonReport,
	GraphOutputDiagnostic,
	GraphOutputDocumentSummary,
	GraphOutputEdgeSummary,
	GraphOutputFilter,
	GraphOutputFormat,
	GraphOutputInput,
	GraphOutputNodeSummary,
	GraphOutputOptions,
	GraphOutputPhaseSummary,
	GraphOutputRenderMode,
	GraphOutputResult,
	GraphOutputRow,
	GraphOutputScope,
	GraphOutputSection,
	GraphOutputStalenessItem,
	GraphOutputStatus,
	GraphOutputSummary,
	GraphTextReport,
} from './dependency-graph/index.js';
export {
	buildDocumentDependencyGraph,
	createInspectableGraphOutput,
	getCanonicalOutputForDocument,
	getDerivedArtifactsForDocument,
	getDirectDependencies,
	getDirectDependents,
	getDocumentNode,
	getDownstreamNodes,
	getExecutiveOutputs,
	getNode,
	getOutputsForDocument,
	getPhaseDocuments,
	getTopologicalDocumentOrder,
	getUpstreamNodes,
	renderGraphJsonReport,
	renderGraphTextReport,
	summarizeDependencyGraph,
} from './dependency-graph/index.js';

// ---------------------------------------------------------------------------
// Step 7.2 — Staleness Detection
// ---------------------------------------------------------------------------

export type {
	ArtifactStalenessRecord,
	DocumentStalenessRecord,
	StalenessComparison,
	StalenessDependencyImpact,
	StalenessDetectionInput,
	StalenessDetectionOptions,
	StalenessDetectionResult,
	StalenessDiagnostic,
	StalenessFingerprint,
	StalenessReason,
	StalenessReasonCode,
	StalenessSeverity,
	StalenessSourceKind,
	StalenessStatus,
	StalenessSummary,
	StalenessTarget,
	StalenessTargetKind,
} from './staleness/index.js';
export {
	buildStalenessStatusSummary,
	compareStalenessStatus,
	computeArtifactMetadataFingerprint,
	computeDependencyGraphFingerprint,
	computeDocumentDescriptorFingerprint,
	computeGeneratedMetadataFingerprint,
	computeProfileContractFingerprint,
	computeRelevantStateFingerprint,
	computeStableFingerprint,
	computeStringFingerprint,
	detectStaleness,
	graphKindToStalenessTargetKind,
} from './staleness/index.js';

// ---------------------------------------------------------------------------
// Step 7.3 — Regeneration Planning
// ---------------------------------------------------------------------------

export type {
	RegenerationPlan,
	RegenerationPlanAction,
	RegenerationPlanBlockedReason,
	RegenerationPlanDependency,
	RegenerationPlanDiagnostic,
	RegenerationPlanDryRunSummary,
	RegenerationPlanInput,
	RegenerationPlanItem,
	RegenerationPlanOptions,
	RegenerationPlanReason,
	RegenerationPlanReasonCode,
	RegenerationPlanResult,
	RegenerationPlanSkippedReason,
	RegenerationPlanSourceChange,
	RegenerationPlanStatus,
	RegenerationPlanSummary,
	RegenerationPlanTargetKind,
} from './regeneration/index.js';
export {
	createRegenerationPlan,
	summarizeRegenerationPlan,
} from './regeneration/index.js';

// ---------------------------------------------------------------------------
// Step 8.1 — Provenance, Decisions, and Open Questions
// ---------------------------------------------------------------------------

export type {
	AssumptionSourceReference,
	ClaimConfidence,
	ClaimEvidence,
	ClaimId,
	ClaimLocation,
	ClaimQuery,
	ClaimQueryResult,
	ClaimRecord,
	ClaimResolutionDiagnostic,
	ClaimResolutionResult,
	ClaimReviewState,
	ClaimSourceLink,
	ClaimSourceLinkType,
	ClaimStatus,
	ClaimType,
	ConversationAnswerSourceReference,
	DecisionSourceReference,
	DocumentSectionClaim,
	DocumentSourceReference,
	ExecutiveItemClaim,
	ExternalReference,
	GeneratedContentClaim,
	ManualNoteSourceReference,
	ProfileDescriptorReference,
	ProvenanceBuilderContext,
	ProvenanceGraph,
	ProvenanceQueryContext,
	ProvenanceSummary,
	RepositoryScanReference,
	SourceConfidence,
	SourceId,
	SourceLocation,
	SourceMetadata,
	SourceRecord,
	SourceReference,
	SourceResolutionDiagnostic,
	SourceResolutionResult,
	SourceResolutionStatus,
	SourceStatus,
	SourceTimestamp,
	SourceType,
	ValidationFindingSourceReference,
} from './provenance/index.js';
export {
	buildClaimSourceLinks,
	buildExecutiveItemProvenanceClaim,
	buildGeneratedSectionClaim,
	buildProvenanceGraph,
	CLAIM_CONFIDENCE_ORDER,
	CLAIM_CONFIDENCES,
	CLAIM_REVIEW_STATES,
	CLAIM_SOURCE_LINK_TYPES,
	CLAIM_STATUS_ORDER,
	CLAIM_STATUSES,
	CLAIM_TYPE_ORDER,
	CLAIM_TYPES,
	ClaimConfidenceSchema,
	ClaimQuerySchema,
	ClaimRecordSchema,
	ClaimReviewStateSchema,
	ClaimStatusSchema,
	ClaimTypeSchema,
	claimFromAssumption,
	claimFromDecision,
	claimFromExecutiveItemDraft,
	claimFromGeneratedSection,
	claimFromOpenQuestion,
	claimFromRisk,
	claimFromValidationFinding,
	LINK_TYPE_ORDER,
	resetProvenanceIdCounter,
	resolveClaimsForDocument,
	resolveClaimsForSource,
	resolveProvenanceForArtifact,
	resolveSourceById,
	resolveSourcesForClaim,
	resolveSourcesForDocument,
	resolveSourcesForGeneratedSection,
	SOURCE_CONFIDENCES,
	SOURCE_STATUSES,
	SOURCE_TYPE_ORDER,
	SOURCE_TYPES,
	SourceConfidenceSchema,
	SourceRecordSchema,
	SourceReferenceSchema,
	SourceStatusSchema,
	SourceTypeSchema,
	sourceFromAssumption,
	sourceFromConfirmedDecision,
	sourceFromConversationAnswer,
	sourceFromDocumentDescriptor,
	sourceFromExternalReference,
	sourceFromManualNote,
	sourceFromProfileDescriptor,
	sourceFromRepositoryScan,
	sourceFromValidationFinding,
	summarizeProvenance,
	validateClaimRecord,
	validateClaimSourceLink,
	validateSourceRecord,
} from './provenance/index.js';

// ---------------------------------------------------------------------------
// Step 8.2 — Registers
// ---------------------------------------------------------------------------

export type {
	AnyRegisterItem,
	AssumptionRegisterItem,
	AssumptionStatus,
	DecisionRegisterItem,
	DecisionStatus,
	HypothesisRegisterItem,
	HypothesisStatus,
	OpenQuestionRegisterItem,
	OpenQuestionStatus,
	RegisterAffectedDocumentLink,
	RegisterCollections,
	RegisterConfidence,
	RegisterCountsByConfidence,
	RegisterCountsByReviewState,
	RegisterCountsByStatus,
	RegisterGenerationImpact,
	RegisterImpactSummary,
	RegisterItem,
	RegisterItemId,
	RegisterKind,
	RegisterKindSummary,
	RegisterLifecycleEvent,
	RegisterLifecycleEventType,
	RegisterLifecycleTransition,
	RegisterOperationDiagnostic,
	RegisterOperationInput,
	RegisterOperationListResult,
	RegisterOperationResult,
	RegisterQuery,
	RegisterQueryResult,
	RegisterReviewState,
	RegisterSharedStatus,
	RegisterSourceLink,
	RegisterStatus,
	RegisterSummary,
	RegisterValidationSummary,
	RiskStatus,
} from './registers/index.js';

export {
	AnyRegisterItemSchema,
	AssumptionRegisterItemSchema,
	acceptRisk,
	activateHypothesis,
	collectTokenFindings,
	computeRegisterImpact,
	computeRegisterImpactSummary,
	confirmRegisterItem,
	createRegisterItem,
	DecisionRegisterItemSchema,
	getAffectedDocumentsForRegisterItem,
	getAssumptionRegister,
	getBlockingOpenQuestions,
	getDecisionRegister,
	getHypothesisRegister,
	getOpenQuestionRegister,
	getRegisterItem,
	getRegisterItemsAffectingDocument,
	getRegisterItemsByDocument,
	getRegisterItemsBySource,
	getRegisterItemsByStatus,
	getReviewRequiredRegisterItems,
	getRiskRegister,
	HypothesisRegisterItemSchema,
	invalidateHypothesis,
	linkRegisterItemToAffectedDocument,
	linkRegisterItemToSource,
	listRegisterItems,
	looksLikeTokenValue,
	markHypothesisInconclusive,
	mitigateRisk,
	OpenQuestionRegisterItemSchema,
	proposeRegisterItem,
	queryRegisters,
	REGISTER_CONFIDENCE_ORDER,
	REGISTER_CONFIDENCES,
	REGISTER_KIND_ORDER,
	REGISTER_KINDS,
	REGISTER_LIFECYCLE_EVENT_TYPE_ORDER,
	REGISTER_REVIEW_STATE_ORDER,
	REGISTER_REVIEW_STATES,
	REGISTER_STATUS_ORDER,
	RegisterAffectedDocumentLinkSchema,
	RegisterConfidenceSchema,
	RegisterKindSchema,
	RegisterLifecycleEventSchema,
	RegisterLifecycleEventTypeSchema,
	RegisterOperationDiagnosticSchema,
	RegisterOperationInputSchema,
	RegisterReviewStateSchema,
	RegisterSourceLinkSchema,
	RiskRegisterItemSchema,
	redactTokenLikeValue,
	redactTokenValues,
	rejectRegisterItem,
	reopenOpenQuestion,
	resolveOpenQuestion,
	resolveRisk,
	reviseRegisterItem,
	summarizeRegisters,
	summarizeRegistersForDocument,
	summarizeRegistersForStatus,
	supersedeRegisterItem,
	unlinkRegisterItemFromAffectedDocument,
	validateHypothesis,
} from './registers/index.js';

// ---------------------------------------------------------------------------
// Step 8.3 — Contradiction and Boundary Violation Detection
// ---------------------------------------------------------------------------

export type {
	BoundaryViolationKind,
	BoundaryViolationRecord,
	ConsistencyCheckDiagnostic,
	ConsistencyCheckInput,
	ConsistencyCheckOptions,
	ConsistencyCheckResult,
	ConsistencyEvidence,
	ConsistencyEvidenceLink,
	ConsistencyRule,
	ConsistencyRuleCategory,
	ConsistencyRuleId,
	ConsistencySummary,
	ConsistencyViolation,
	ContradictionKind,
	ContradictionRecord,
	ExportReadinessBlocker,
	ExportReadinessStatus,
	GeneratedOutputMetadataEntry,
	GenerationReportSummary,
} from './consistency/index.js';

export {
	CONSISTENCY_RULE_ORDER,
	getAllConsistencyRules,
	getConsistencyRuleById,
	runConsistencyCheck,
} from './consistency/index.js';

// ---------------------------------------------------------------------------
// Step 9.1 — HTML Artifact Planner
// ---------------------------------------------------------------------------

export type {
	HtmlArtifactAction,
	HtmlArtifactBlocker,
	HtmlArtifactDeclaration,
	HtmlArtifactDeclarationSource,
	HtmlArtifactDependency,
	HtmlArtifactDiagnostic,
	HtmlArtifactKind,
	HtmlArtifactOutputPath,
	HtmlArtifactPlan,
	HtmlArtifactPlanInput,
	HtmlArtifactPlanItem,
	HtmlArtifactPlanOptions,
	HtmlArtifactPlanResult,
	HtmlArtifactReadiness,
	HtmlArtifactReasonCode,
	HtmlArtifactSource,
	HtmlArtifactSourceKind,
	HtmlArtifactStatus,
	HtmlArtifactSummary,
} from './html/index.js';
export {
	createHtmlArtifactPlan,
	discoverHtmlArtifactDeclarations,
	HTML_ARTIFACT_KIND_ORDER,
	HTML_ARTIFACT_STATUS_ORDER,
	isHtmlOutputPathSafe,
	resolveHtmlOutputPath,
	summarizeHtmlArtifactPlan,
} from './html/index.js';

// ---------------------------------------------------------------------------
// Step 9.2 — Safe Static HTML Renderer
// ---------------------------------------------------------------------------

export type {
	HtmlEscapedString,
	HtmlRenderArtifact,
	HtmlRenderBoundary,
	HtmlRenderDecisionData,
	HtmlRenderDiagnostic,
	HtmlRenderDocumentData,
	HtmlRendererMetadata,
	HtmlRendererTheme,
	HtmlRenderInput,
	HtmlRenderOptions,
	HtmlRenderPhaseData,
	HtmlRenderResult,
	HtmlRenderRiskData,
	HtmlRenderSection,
	HtmlRenderSectionKind,
	HtmlRenderSecuritySummary,
	HtmlRenderSource,
	HtmlRenderStatus,
	HtmlRenderSummaryData,
	HtmlRenderTraceabilityClaimItem,
	HtmlRenderTraceabilityData,
	HtmlRenderTraceabilitySourceItem,
	HtmlRenderValidationFindingData,
	HtmlTrustedTemplate,
	SanitizedHrefResult,
	StaticHtmlRenderer,
} from './html/index.js';
export {
	buildDocumentWrappers,
	createStaticHtmlRenderer,
	DEFAULT_HTML_RENDERER_THEME,
	escapeHtmlAttribute,
	escapeHtmlText,
	escapePathForDisplay,
	HTML_RENDER_BOUNDARY_ORDER,
	HTML_RENDER_SECTION_KIND_ORDER,
	HTML_RENDER_STATUS_ORDER,
	isUnsafeHtmlAttribute,
	looksLikeSecretValue,
	markAsTrusted,
	normalizePathSeparators,
	redactSecretString,
	renderDecisionListSection,
	renderDerivedArtifactWarning,
	renderDiagnosticsSection,
	renderDocumentListSection,
	renderEmptyStateSection,
	renderHtmlDocument,
	renderHtmlDocumentEnd,
	renderHtmlDocumentStart,
	renderMetadataBlock,
	renderPhaseListSection,
	renderReadinessStatusSection,
	renderRiskListSection,
	renderSourceReferencesSection,
	renderStaticHtmlArtifact,
	renderSummarySection,
	renderThemeCss,
	renderTraceabilitySection,
	renderValidationFindingsSection,
	sanitizeLocalHref,
	sanitizeTextContent,
	staticHtmlRenderer,
} from './html/index.js';

// ---------------------------------------------------------------------------
// Step 10.1 — Agent Pack Planner
// ---------------------------------------------------------------------------

export type {
	AgentPackAction,
	AgentPackBlocker,
	AgentPackDeclaration,
	AgentPackDeclarationSource,
	AgentPackDependency,
	AgentPackDiagnostic,
	AgentPackKind,
	AgentPackOutputPath,
	AgentPackPlan,
	AgentPackPlanInput,
	AgentPackPlanItem,
	AgentPackPlanOptions,
	AgentPackPlanResult,
	AgentPackReadiness,
	AgentPackReasonCode,
	AgentPackRequiredContext,
	AgentPackSource,
	AgentPackSourceKind,
	AgentPackStatus,
	AgentPackSummary,
} from './agent-packs/index.js';
export {
	AGENT_PACK_KIND_ORDER,
	AGENT_PACK_STATUS_ORDER,
	createAgentPackPlan,
	discoverAgentPackDeclarations,
	isAgentPackOutputPathSafe,
	resolveAgentPackOutputPath,
	summarizeAgentPackPlan,
} from './agent-packs/index.js';

// ---------------------------------------------------------------------------
// Step 10.2 — Bounded Context Bundle
// ---------------------------------------------------------------------------

export type {
	ContextBundle,
	ContextBundleAcceptanceCriterion,
	ContextBundleAcceptanceCriterionInput,
	ContextBundleAssumption,
	ContextBundleAssumptionInput,
	ContextBundleBlocker,
	ContextBundleBuilder,
	ContextBundleCanonicalDocMeta,
	ContextBundleConsistencyFinding,
	ContextBundleConsistencyFindingInput,
	ContextBundleConstraint,
	ContextBundleDecision,
	ContextBundleDecisionInput,
	ContextBundleDiagnostic,
	ContextBundleHypothesis,
	ContextBundleHypothesisInput,
	ContextBundleInput,
	ContextBundleMetadata,
	ContextBundleNonGoal,
	ContextBundleNonGoalInput,
	ContextBundleOpenQuestion,
	ContextBundleOpenQuestionInput,
	ContextBundleOptions,
	ContextBundleRedactionSummary,
	ContextBundleRegisterData,
	ContextBundleRequiredChange,
	ContextBundleRequiredChangeInput,
	ContextBundleRequirement,
	ContextBundleResult,
	ContextBundleRisk,
	ContextBundleRiskInput,
	ContextBundleSection,
	ContextBundleSectionItem,
	ContextBundleSectionKind,
	ContextBundleSizeBudget,
	ContextBundleSizeSummary,
	ContextBundleSource,
	ContextBundleSourceKind,
	ContextBundleStatus,
	ContextBundleTraceabilityEntry,
	ContextBundleTraceabilityEntryInput,
	ContextBundleValidationFinding,
	ContextBundleValidationFindingInput,
} from './agent-packs/index.js';
export {
	buildBoundedContextBundle,
	DEFAULT_SCOPE_OPTIONS,
	DEFAULT_SIZE_BUDGET,
} from './agent-packs/index.js';

// ---------------------------------------------------------------------------
// Step 10.3 — Agent Pack Renderer & Generation
// ---------------------------------------------------------------------------

export type {
	AgentPackArtifactRecord,
	AgentPackChangedPath,
	AgentPackGenerationInput,
	AgentPackGenerationItem,
	AgentPackGenerationOptions,
	AgentPackGenerationReport,
	AgentPackGenerationResult,
	AgentPackGenerationStatus,
	AgentPackRenderDiagnostic,
	AgentPackRenderedMarkdown,
	AgentPackRenderInput,
	AgentPackRenderMetadata,
	AgentPackRenderOptions,
	AgentPackRenderResult,
	AgentPackRenderSection,
	AgentPackRenderSectionKind,
	AgentPackSecuritySummary,
	AgentPackTemplate,
	AgentPackTemplateKind,
	AgentPackWritePolicy,
} from './agent-packs/index.js';
export {
	AGENT_PACK_TEMPLATE_KIND_ORDER,
	buildAgentPackArtifactRecords,
	checkAgentPackSecurity,
	generateAgentPacks,
	generateAgentPacksAsync,
	isPathTraversalSuspected,
	mapPackKindToTemplateKind,
	renderAgentPack,
	SECTION_SORT_ORDER,
} from './agent-packs/index.js';

// ---------------------------------------------------------------------------
// Step 11.1 — Executive Readiness Gate
// ---------------------------------------------------------------------------

export type {
	ExecutiveCompilationGateStatus,
	ExecutiveReadinessReport,
	ExecutiveReadinessRequirement,
	ExecutiveReadinessRequirementStatus,
	NormativeBaselineBlockerKind,
	NormativeBaselineDocumentReadiness,
	NormativeBaselineExecutiveScopeCheck,
	NormativeBaselinePhaseReadiness,
	NormativeBaselineReadinessBlocker,
	NormativeBaselineReadinessDiagnostic,
	NormativeBaselineReadinessInput,
	NormativeBaselineReadinessOptions,
	NormativeBaselineReadinessResult,
	NormativeBaselineReadinessStatus,
	NormativeBaselineReadinessSummary,
	NormativeBaselineReadinessWarning,
	NormativeBaselineRegisterCoverage,
	NormativeBaselineSourceCoverage,
	NormativeBaselineStalenessCoverage,
	NormativeBaselineTraceabilityCoverage,
	NormativeBaselineValidationCoverage,
	NormativeBaselineWarningKind,
} from './executive/index.js';
export {
	assertExecutiveCompilationAllowed,
	BLOCKER_KIND_ORDER,
	COMPILATION_GATE_ORDER,
	DERIVED_ARTIFACT_TYPES,
	EXECUTIVE_PHASE_TO_STANDARD,
	evaluateNormativeBaselineReadiness,
	READINESS_STATUS_ORDER,
	REQUIREMENT_CATEGORY_ORDER,
	SEVERITY_ORDER,
	WARNING_KIND_ORDER,
} from './executive/index.js';

// ---------------------------------------------------------------------------
// Step 11.2 — Executive Plan JSON Compilation
// ---------------------------------------------------------------------------

export type {
	ExecutivePlanAcceptanceCriterion,
	ExecutivePlanBlocker,
	ExecutivePlanChangedPath,
	ExecutivePlanCompilationMode,
	ExecutivePlanCompilationStatus,
	ExecutivePlanCompileInput,
	ExecutivePlanCompileOptions,
	ExecutivePlanCompileResult,
	ExecutivePlanDependency,
	ExecutivePlanDiagnostic,
	ExecutivePlanExportMetadata,
	ExecutivePlanGenerationResult,
	ExecutivePlanItemOrigin,
	ExecutivePlanItemPriority,
	ExecutivePlanItemStatus,
	ExecutivePlanItemType,
	ExecutivePlanJson,
	ExecutivePlanJsonArtifact,
	ExecutivePlanJsonConfidenceLevel,
	ExecutivePlanJsonDecision,
	ExecutivePlanJsonExportConfig,
	ExecutivePlanJsonInitiative,
	ExecutivePlanJsonItem,
	ExecutivePlanJsonMilestone,
	ExecutivePlanJsonProject,
	ExecutivePlanJsonRisk,
	ExecutivePlanJsonRoadmap,
	ExecutivePlanJsonSource,
	ExecutivePlanJsonWorkstream,
	ExecutivePlanMilestone,
	ExecutivePlanPhase,
	ExecutivePlanReadinessSnapshot,
	ExecutivePlanRisk,
	ExecutivePlanSourceReference,
	ExecutivePlanSuggestedExecutor,
	ExecutivePlanTraceability,
	ExecutivePlanWorkItem,
	ExecutivePlanWorkItemKind,
	ExecutivePlanWorkItemStatus,
} from './executive/index.js';
export {
	assertExecutiveCompilation,
	compileExecutivePlan,
	ITEM_TYPE_ORDER,
	WORK_ITEM_KIND_ORDER,
	WORK_ITEM_KIND_TO_SCHEMA_TYPE,
} from './executive/index.js';

// ---------------------------------------------------------------------------
// Step 11.3 — Executive Export Adapters
// ---------------------------------------------------------------------------

export type {
	ExecutiveExportAdapter,
	ExecutiveExportAdapterKind,
	ExecutiveExportArtifactRecord,
	ExecutiveExportChangedPath,
	ExecutiveExportDiagnostic,
	ExecutiveExportGenerationInput,
	ExecutiveExportGenerationItem,
	ExecutiveExportGenerationOptions,
	ExecutiveExportGenerationResult,
	ExecutiveExportGenerationStatus,
	ExecutiveExportInput,
	ExecutiveExportMapping,
	ExecutiveExportMappingFile,
	ExecutiveExportMappingLoadResult,
	ExecutiveExportMappingOutput,
	ExecutiveExportMappingTarget,
	ExecutiveExportOptions,
	ExecutiveExportRenderedFile,
	ExecutiveExportReport,
	ExecutiveExportResult,
	ExecutiveExportResultMetadata,
	ExecutiveExportSecurityCheck,
	ExecutiveExportSecuritySummary,
	ExecutiveExportSupportStatus,
	ExecutiveExportTarget,
	ExecutiveExportWritePolicy,
	KnownMappingEntry,
} from './executive/index.js';
export {
	ADAPTER_KIND_ORDER,
	executiveAgentPackExportAdapter,
	executiveGitHubIssuesExportAdapter,
	executiveHtmlExportAdapter,
	executiveMarkdownExportAdapter,
	generateExecutiveExports,
	getKnownMappingEntries,
	isPlannedAdapterContract,
	isSupportedFileExport,
	loadExecutiveExportMappings,
	loadKnownMappings,
	sortExportTargets,
} from './executive/index.js';

// ---------------------------------------------------------------------------
// Step 11.4 — Executive Compile Workflow
// ---------------------------------------------------------------------------

export type {
	ExecutiveCompileAction,
	ExecutiveCompileChangedPath,
	ExecutiveCompileDiagnostic,
	ExecutiveCompileInput,
	ExecutiveCompileMode,
	ExecutiveCompileOptions,
	ExecutiveCompilePlan,
	ExecutiveCompilePreflight,
	ExecutiveCompileReport,
	ExecutiveCompileResult,
	ExecutiveCompileRunMetadata,
	ExecutiveCompileStatus,
	ExecutiveCompileTarget,
	ExecutiveCompileTargetKind,
	ExecutiveCompileTargetStatus,
} from './executive/index.js';
export {
	COMPILE_TARGET_TO_ADAPTER,
	executiveCompileWorkflow,
} from './executive/index.js';

// ---------------------------------------------------------------------------
// Step 12.1 — Existing Documentation Import Planner
// ---------------------------------------------------------------------------

export type {
	DocumentationImportActionKind,
	DocumentationImportBlocker,
	DocumentationImportCandidate,
	DocumentationImportCandidateKind,
	DocumentationImportCandidateSource,
	DocumentationImportCandidateStatus,
	DocumentationImportConflict,
	DocumentationImportConflictKind,
	DocumentationImportDiagnostic,
	DocumentationImportMapping,
	DocumentationImportMappingEvidence,
	DocumentationImportMappingStatus,
	DocumentationImportMetadata,
	DocumentationImportPathPolicy,
	DocumentationImportPlan,
	DocumentationImportPlanInput,
	DocumentationImportPlanner,
	DocumentationImportPlanOptions,
	DocumentationImportPlanResult,
	DocumentationImportProposedAction,
	DocumentationImportReadiness,
	DocumentationImportScope,
	DocumentationImportSummary,
	DocumentationImportWarning,
} from './import/index.js';
export {
	checkImportPathSafety,
	classifyImportCandidates,
	computeCandidateId,
	computeStringChecksum,
	contentLooksLikeDerivedArtifact,
	contentLooksLikeTranscript,
	DEFAULT_IMPORT_PATH_POLICY,
	detectImportConflicts,
	discoverImportCandidates,
	extractCandidateMetadata,
	getPathExtension,
	hasSecretLikeContent,
	IMPORT_ACTION_KIND_ORDER,
	IMPORT_CANDIDATE_KIND_ORDER,
	IMPORT_CANDIDATE_STATUS_ORDER,
	IMPORT_CONFLICT_KIND_ORDER,
	IMPORT_MAPPING_STATUS_ORDER,
	IMPORT_READINESS_ORDER,
	isExtensionAllowed,
	isPathTraversal,
	mapImportCandidates,
	normalizeImportPath,
	pathLooksLikeDerivedArtifact,
	planDocumentationImport,
	redactImportContent,
	resolveImportPathPolicy,
	safeContentSnippet,
	scanForSecrets,
	toRelativeImportPath,
} from './import/index.js';

// ---------------------------------------------------------------------------
// Step 12.2 — Repository Scanner
// ---------------------------------------------------------------------------

export type {
	RepositoryScanArtifact,
	RepositoryScanArtifactKind,
	RepositoryScanBoundarySummary,
	RepositoryScanChangedPath,
	RepositoryScanCiSummary,
	RepositoryScanConfigSummary,
	RepositoryScanDiagnostic,
	RepositoryScanDocumentationSummary,
	RepositoryScanFinding,
	RepositoryScanFindingKind,
	RepositoryScanInput,
	RepositoryScanner,
	RepositoryScanOptions,
	RepositoryScanPackageSummary,
	RepositoryScanPolicy,
	RepositoryScanReport,
	RepositoryScanResult,
	RepositoryScanScope,
	RepositoryScanSecuritySummary,
	RepositoryScanSeverity,
	RepositoryScanSummary,
	RepositoryScanTarget,
	RepositoryScanTargetKind,
	RepositoryScanToolingSummary,
	RepositoryScanWorkspaceSummary,
	ScannerFsAdapter,
} from './scanner/index.js';
export {
	buildScanReport,
	checkFileCountLimit,
	checkFileSizeLimit,
	checkPathSafe,
	checkRecursionDepth,
	computeScanFindingCounts,
	computeScanSummary,
	createPolicyLimitDiagnostic,
	createScanDiagnostic,
	createScanFinding,
	isDirectoryIgnored,
	isExtensionAllowed as isScannerExtensionAllowed,
	KNOWN_METADATA_FILENAMES,
	nextFindingId,
	redactSecretContent,
	resetFindingCounter,
	resolveScanPolicy,
	SCAN_ARTIFACT_KIND_ORDER,
	SCAN_FINDING_KIND_ORDER,
	SCAN_TARGET_KIND_ORDER,
	safeRelativePath,
	scanForSecrets as scanFileForSecrets,
	scanRepository,
	sortScanFindings,
} from './scanner/index.js';

// ---------------------------------------------------------------------------
// Step 12.3 — Docs-vs-Code Consistency Checks
// ---------------------------------------------------------------------------

export type {
	DocsCodeArtifactBoundaryCheck,
	DocsCodeBoundaryCheck,
	DocsCodeCategorySummary,
	DocsCodeChangedPath,
	DocsCodeClaim,
	DocsCodeClaimKind,
	DocsCodeClaimSource,
	DocsCodeCommandCheck,
	DocsCodeComparison,
	DocsCodeComparisonStatus,
	DocsCodeConsistencyChecker,
	DocsCodeConsistencyDiagnostic,
	DocsCodeConsistencyFinding,
	DocsCodeConsistencyFindingKind,
	DocsCodeConsistencyInput,
	DocsCodeConsistencyOptions,
	DocsCodeConsistencyReport,
	DocsCodeConsistencyResult,
	DocsCodeConsistencySeverity,
	DocsCodeConsistencySummary,
	DocsCodeEvidence,
	DocsCodeObservedFact,
	DocsCodeObservedFactKind,
	DocsCodeProfileCheck,
	DocsCodeRecoveryHint,
	DocsCodeRootCheck,
	DocsCodeScriptCheck,
	DocsCodeSecurityCheck,
} from './consistency/index.js';
export {
	buildDocsCodeConsistencyReport,
	buildObservedFacts,
	claimKindToCategory,
	compareDocsCodeSeverity,
	extractDocsClaims,
	findingKindToCategory,
	isScriptMutating,
	nextDocsCodeId,
	resetDocsCodeIdCounter,
	runDocsCodeConsistencyCheck,
	sortDocsCodeFindings,
} from './consistency/index.js';

// ---------------------------------------------------------------------------
// Step 12.4 — Candidate Fact/Decision Extraction
// ---------------------------------------------------------------------------

export type {
	CandidateExtractedAcceptanceCriterion,
	CandidateExtractedAssumption,
	CandidateExtractedConstraint,
	CandidateExtractedDecision,
	CandidateExtractedEvidenceReference,
	CandidateExtractedFact,
	CandidateExtractedHypothesis,
	CandidateExtractedItem,
	CandidateExtractedItemBase,
	CandidateExtractedItemConfidence,
	CandidateExtractedItemKind,
	CandidateExtractedItemStatus,
	CandidateExtractedNonGoal,
	CandidateExtractedOpenQuestion,
	CandidateExtractedRequirement,
	CandidateExtractedRisk,
	CandidateExtractionActionKind,
	CandidateExtractionBlocker,
	CandidateExtractionChangedPath,
	CandidateExtractionConflict,
	CandidateExtractionConflictKind,
	CandidateExtractionDiagnostic,
	CandidateExtractionEvidence,
	CandidateExtractionInput,
	CandidateExtractionOptions,
	CandidateExtractionReadiness,
	CandidateExtractionResult,
	CandidateExtractionReviewAction,
	CandidateExtractionSource,
	CandidateExtractionSourceKind,
	CandidateExtractionSummary,
	CandidateExtractionWarning,
	CandidateFactDecisionExtractor,
} from './import/index.js';
export {
	CANDIDATE_EXTRACTED_ITEM_CONFIDENCE_ORDER,
	CANDIDATE_EXTRACTED_ITEM_KIND_ORDER,
	CANDIDATE_EXTRACTED_ITEM_STATUS_ORDER,
	CANDIDATE_EXTRACTION_ACTION_KIND_ORDER,
	CANDIDATE_EXTRACTION_CONFLICT_KIND_ORDER,
	CANDIDATE_EXTRACTION_READINESS_ORDER,
	CANDIDATE_EXTRACTION_SOURCE_KIND_ORDER,
	contentLooksLikeDerivedArtifactExtraction,
	contentLooksLikeTranscriptExtraction,
	extractCandidateFactsAndDecisions,
	getExtractionIdCounter,
	nextExtractionId,
	pathLooksLikeDerivedArtifactExtraction,
	RECOGNIZED_FRONTMATTER_KEYS,
	RECOGNIZED_HEADINGS,
	resetExtractionIdCounter,
} from './import/index.js';
